# Generated by Django 4.2.2 on 2023-06-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la region')),
                ('nombreComuna', models.CharField(max_length=30, verbose_name='Nombre de la comuna')),
                ('costoDespacho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la pregunta')),
                ('pregunta', models.CharField(max_length=30, verbose_name='Pregunta del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del rol')),
                ('nombreRol', models.CharField(max_length=20, verbose_name='Rol del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nombreUsuario', models.CharField(max_length=20, verbose_name='Nombre del usuario')),
                ('apellidoUsuario', models.CharField(max_length=20, verbose_name='Apellido del usuario')),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=30, verbose_name='Contraseña del usuario')),
                ('respuesta', models.CharField(max_length=30, verbose_name='Respuesta de la pregunta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pregunta')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la Region')),
                ('nombreRegion', models.CharField(max_length=30, verbose_name='Nombre de la región')),
                ('localidad', models.CharField(max_length=30, verbose_name='Localidad de la región')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('descripcionProducto', models.CharField(max_length=50, verbose_name='Descripcion Producto')),
                ('precioProducto', models.IntegerField()),
                ('stockProducto', models.IntegerField()),
                ('tallaProducto', models.CharField(max_length=10, verbose_name='Talla del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la foto')),
                ('nombreFoto', models.CharField(max_length=20, verbose_name='Nombre de la foto')),
                ('imagen', models.ImageField(upload_to='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la direccion')),
                ('calle', models.CharField(max_length=30, verbose_name='Calle')),
                ('nombreVillaPoblacion', models.CharField(max_length=30, verbose_name='Nombre de la Calle')),
                ('numeroCalle', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del detalle de compra')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.direccion'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de compra')),
                ('fechaCompra', models.DateField()),
                ('fechaDespacho', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('estado', models.CharField(max_length=30, verbose_name='Estado de la compra')),
                ('total', models.IntegerField()),
                ('costoDespecho', models.IntegerField()),
                ('carrito', models.IntegerField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.detalle')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
    ]
